### ISSUE TITLE
Description rendered as ${1} instead of text

### ISSUE THREAD

**Issue by k8n** [steamlead/grav-plugin-autoseo#7]
[trng](http://php.net/manual/en/function.mb-ereg-replace.php#104440):
> You can use \\n for capture group in replacement.
> And you can NOT use $n notation (unlike preg_replace function).

https://github.com/gameamea/grav-plugin-autoseo/blob/7c0eb3c5ceccf79ac4d4d941fc30698790d31706/autoseo.php#L225

**Comment by LaurentOngaro** [comment]
I'll look at this issue as soon as possible, but I'm really busy at this time.
I've not fully tested this 1.3.6 (latest at this time) release. But the previous one did not have this issue
so you can still use the 1.3.5 version to fix that.

**Comment by fbrinker** [comment]
@LaurentOngaro Is a new release necessary to update the plugins for users? Could you create one for this fix? At least for me it was a "blocker" :)
