### ISSUE TITLE
Issue with UTF8 substringing

### ISSUE THREAD

**Issue by k8n** [steamlead/grav-plugin-autoseo#8]
In my case, broken utf8 strings when fed to grav-plugin-minify-html cause removal of part of html content of pages.

Should probably use [mb_substr](http://php.net/manual/en/function.mb-substr.php).

[Example](https://stackoverflow.com/a/9087570/497988)

[Offending instance in autoseo](https://github.com/gameamea/grav-plugin-autoseo/blob/7c0eb3c5ceccf79ac4d4d941fc30698790d31706/autoseo.php#L173)

**Comment by k8n** [comment]
I'm noting that grav core has [utility functions to truncate text](https://github.com/getgrav/grav/blob/df7e9b9c1f544ad5fc3cf4b4227df9d1361f8f2b/system/src/Grav/Common/Utils.php#L255) that already use mb_substr.

**Comment by LaurentOngaro** [comment]
code merged
